[package]
name = "aoc"
version = "0.1.0"
authors = ["Kostas Kolivas <kkolivas@skroutz.gr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = ""
regex = "1.4"
